jobs:
  ci/unit:
    description: "Run unit test"

  ci/bench:
    description: "Run benchmark test"

  ci/lint/vet:
    description: "Run go vet"

  ci/lint/staticcheck:
    description: "Run staticcheck"

  ci/lint/golangci-lint:
    description: "Run golangci-lint"

  lint:
    description: "Run static code analysis"
    job:
      - {from: [ci/lint/vet, ci/lint/staticcheck, ci/lint/golangci-lint]}

  default:
    job:
      - {from: [lint], to: [ci/unit]}
