jobs:
  ci/unit:
    description: "Run unit test"

  ci/bench:
    description: "Run benchmark test"

  ci/lint/vet:
    description: "Run go vet"

  ci/lint/staticcheck:
    description: "Run staticcheck"

  lint:
    description: "Run static code analysis"
    job:
      - {from: [ci/lint/vet, ci/lint/staticcheck]}

  default:
    job:
      - {from: [lint], to: [ci/unit]}
