jobs:
  ci/unit:
    description: "Run unit test"

  ci/bench:
    description: "Run benchmark test"

  ci/vet:
    description: "Run go vet"

  lint:
    description: "Run static code analysis"
    job:
      - {from: [ci/vet]}

  default:
    job:
      - {from: [lint], to: [ci/unit]}
